2021-08-26 16:05:06,452 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-26 16:09:14,990 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-26 16:09:26,000 interview.admin 46 INFO     admin exported 1 candidate records 
2021-08-27 16:15:49,917 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-27 16:17:25,405 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 01:15:30,594 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 01:19:26,389 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/models.py changed, reloading.
2021-08-28 01:19:27,055 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 01:21:41,734 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-28 01:21:42,199 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 01:27:35,208 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-28 01:27:35,842 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 01:38:45,122 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-28 01:38:45,746 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 02:10:48,633 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 02:11:00,358 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1697, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/liuhao/PythonProject/recruitment/interview/admin.py", line 74, in get_changelist_instance
    self.list_editable = self.get_list_editable(request)
  File "/Users/liuhao/PythonProject/recruitment/interview/admin.py", line 69, in get_list_editable
    if request.user.is_super_user or 'hr' in groups_names:
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/functional.py", line 247, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'is_super_user'
2021-08-28 02:13:16,218 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-28 02:13:16,870 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 02:13:32,316 django.request 224 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1697, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/Users/liuhao/PythonProject/recruitment/interview/admin.py", line 74, in get_changelist_instance
    self.list_editable = self.get_list_editable(request)
  File "/Users/liuhao/PythonProject/recruitment/interview/admin.py", line 70, in get_list_editable
    return self.default_list_editable
AttributeError: 'CandidateAdmin' object has no attribute 'default_list_editable'
2021-08-28 02:15:18,093 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-28 02:15:18,638 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 02:17:39,146 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/settings/base.py changed, reloading.
2021-08-28 02:17:39,730 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 07:05:38,858 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-28 07:05:39,535 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 07:10:42,618 django.request 224 ERROR    Internal Server Error: /admin/auth/user/2/change/
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xE4\\xB8\\x80\\xE9\\x9D\\xA2...' for column 'first_name' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1660, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1540, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1586, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1099, in save_model
    obj.save()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 67, in save
    super().save(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/models/base.py", line 899, in _do_update
    return filtered._update(values) > 0
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xE4\\xB8\\x80\\xE9\\x9D\\xA2...' for column 'first_name' at row 1")
2021-08-28 07:50:51,182 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 08:02:47,978 django_python3_ldap.ldap 196 WARNING  LDAP bind failed: socket connection error while opening: [Errno 61] Connection refused
2021-08-28 08:02:47,978 django_python3_ldap.ldap 196 WARNING  LDAP bind failed: socket connection error while opening: [Errno 61] Connection refused
2021-08-28 08:03:19,275 django_python3_ldap.ldap 196 WARNING  LDAP bind failed: socket connection error while opening: [Errno 61] Connection refused
2021-08-28 08:03:19,275 django_python3_ldap.ldap 196 WARNING  LDAP bind failed: socket connection error while opening: [Errno 61] Connection refused
2021-08-28 08:04:23,708 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/models.py changed, reloading.
2021-08-28 08:04:24,474 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 08:05:08,467 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/models.py changed, reloading.
2021-08-28 08:05:09,141 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 08:05:41,098 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 08:08:54,539 interview.admin 63 INFO     interviewer is in user's group for 二面面试官
2021-08-28 08:08:54,542 interview.admin 63 INFO     interviewer is in user's group for 二面面试官
2021-08-28 08:09:24,854 interview.admin 63 INFO     interviewer is in user's group for 一面面试官
2021-08-28 08:09:24,857 interview.admin 63 INFO     interviewer is in user's group for 一面面试官
2021-08-28 08:21:09,005 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 08:21:14,952 interview.admin 68 INFO     interviewer is in user's group for 一面面试官
2021-08-28 08:21:14,956 interview.admin 68 INFO     interviewer is in user's group for 一面面试官
2021-08-28 08:22:18,555 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/candidate_fieldset.py changed, reloading.
2021-08-28 08:22:19,056 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 08:22:23,426 interview.admin 68 INFO     interviewer is in user's group for 一面面试官
2021-08-28 08:22:23,430 interview.admin 68 INFO     interviewer is in user's group for 一面面试官
2021-08-28 08:25:55,889 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/candidate_fieldset.py changed, reloading.
2021-08-28 08:25:56,442 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 08:26:02,950 interview.admin 68 INFO     interviewer is in user's group for 一面面试官
2021-08-28 08:26:02,955 interview.admin 68 INFO     interviewer is in user's group for 一面面试官
2021-08-28 08:38:39,663 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-28 08:38:40,330 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 08:45:20,872 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-28 08:45:21,338 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 08:47:40,476 django_python3_ldap.ldap 196 WARNING  LDAP bind failed: socket connection error while opening: [Errno 61] Connection refused
2021-08-28 08:47:40,476 django_python3_ldap.ldap 196 WARNING  LDAP bind failed: socket connection error while opening: [Errno 61] Connection refused
2021-08-28 08:51:23,808 django_python3_ldap.ldap 196 WARNING  LDAP bind failed: socket connection error while opening: [Errno 61] Connection refused
2021-08-28 08:51:23,808 django_python3_ldap.ldap 196 WARNING  LDAP bind failed: socket connection error while opening: [Errno 61] Connection refused
2021-08-28 10:51:27,252 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 10:51:49,837 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 10:52:17,330 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 10:52:19,694 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 10:52:20,476 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 10:52:38,775 django.request 224 WARNING  Not Found: /accounts/accounts/
2021-08-28 10:52:42,917 django.request 224 WARNING  Not Found: /accounts/
2021-08-28 10:53:00,246 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 10:53:28,112 django.request 224 WARNING  Not Found: /register
2021-08-28 10:53:58,531 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 10:54:13,455 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 10:54:49,586 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 10:55:34,835 django.request 224 WARNING  Not Found: /accounts/ register/
2021-08-28 10:55:39,381 django.request 224 WARNING  Not Found: /accounts/ register/
2021-08-28 10:55:44,493 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 10:57:57,895 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 11:00:20,159 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/settings/base.py changed, reloading.
2021-08-28 11:00:21,154 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 11:00:49,968 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 11:01:06,539 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/settings/base.py changed, reloading.
2021-08-28 11:01:07,441 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 11:01:20,138 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 11:02:58,306 django.request 224 WARNING  Not Found: /
2021-08-28 11:03:13,354 django.request 224 WARNING  Not Found: /accounts/
2021-08-28 11:03:20,614 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 11:05:53,204 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/settings/base.py changed, reloading.
2021-08-28 11:05:54,189 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 11:06:08,462 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 11:06:17,970 django.request 224 WARNING  Not Found: /rango/
2021-08-28 11:06:44,132 django.request 224 WARNING  Not Found: /rango/
2021-08-28 11:06:57,368 django.request 224 WARNING  Not Found: /rango/
2021-08-28 11:07:17,554 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/settings/base.py changed, reloading.
2021-08-28 11:07:18,430 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 11:07:20,708 django.request 224 WARNING  Not Found: /accounts/profile/
2021-08-28 11:12:09,510 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/recruitment/urls.py changed, reloading.
2021-08-28 11:12:10,341 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 11:12:18,926 django.request 224 WARNING  Not Found: /
2021-08-28 11:12:29,646 django.request 224 WARNING  Not Found: /
2021-08-28 11:13:41,733 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/urls.py changed, reloading.
2021-08-28 11:13:42,498 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 11:13:50,907 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/urls.py changed, reloading.
2021-08-28 11:13:51,629 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 11:17:45,072 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/recruitment/urls.py changed, reloading.
2021-08-28 11:17:45,975 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 12:00:53,942 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/settings/base.py changed, reloading.
2021-08-28 12:00:54,901 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 12:07:13,752 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/recruitment/urls.py changed, reloading.
2021-08-28 12:07:14,607 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 12:07:37,749 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 12:07:53,511 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/recruitment/urls.py changed, reloading.
2021-08-28 12:07:54,238 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-28 12:08:01,686 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/recruitment/urls.py changed, reloading.
2021-08-28 12:08:02,323 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-29 14:41:09,383 django.security.DisallowedHost 99 ERROR    Invalid HTTP_HOST header: '0.0.0.0:9999'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
2021-08-29 14:41:09,473 django.request 224 WARNING  Bad Request: /
2021-08-29 14:41:09,754 django.security.DisallowedHost 99 ERROR    Invalid HTTP_HOST header: '0.0.0.0:9999'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
2021-08-29 14:41:09,802 django.request 224 WARNING  Bad Request: /favicon.ico
2021-08-29 14:41:21,767 django.security.DisallowedHost 99 ERROR    Invalid HTTP_HOST header: '0.0.0.0:9999'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
2021-08-29 14:41:21,798 django.request 224 WARNING  Bad Request: /admin
2021-08-29 14:41:21,920 django.security.DisallowedHost 99 ERROR    Invalid HTTP_HOST header: '0.0.0.0:9999'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
2021-08-29 14:41:21,951 django.request 224 WARNING  Bad Request: /favicon.ico
2021-08-29 14:41:51,088 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-29 14:41:52,916 django.request 224 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'translate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/PythonProject/recruitment/jobs/views.py", line 24, in joblist
    return HttpResponse(template.render(context))
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'translate'. Did you forget to register or load this tag?
2021-08-29 14:42:19,085 django.request 224 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'translate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/PythonProject/recruitment/jobs/views.py", line 24, in joblist
    return HttpResponse(template.render(context))
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'translate'. Did you forget to register or load this tag?
2021-08-29 14:43:58,908 django.request 224 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'translate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/PythonProject/recruitment/jobs/views.py", line 24, in joblist
    return HttpResponse(template.render(context))
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/defaulttags.py", line 965, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'translate', expected 'elif'，'else' or 'endif'. Did you forget to register or load this tag?
2021-08-29 14:44:35,960 django.request 224 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'blocktranslate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/PythonProject/recruitment/jobs/views.py", line 24, in joblist
    return HttpResponse(template.render(context))
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/defaulttags.py", line 965, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 17: 'blocktranslate', expected 'elif'，'else' or 'endif'. Did you forget to register or load this tag?
2021-08-29 14:47:23,180 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-29 14:47:24,007 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-29 14:47:26,567 django.request 224 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/http/response.py", line 119, in __init__
    self.status_code = int(status)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/PythonProject/recruitment/jobs/views.py", line 24, in joblist
    return HttpResponse(request, 'joblist.html', context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/http/response.py", line 329, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/http/response.py", line 121, in __init__
    raise TypeError('HTTP status code must be an integer.')
TypeError: HTTP status code must be an integer.
2021-08-29 14:47:28,029 django.request 224 ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/http/response.py", line 119, in __init__
    self.status_code = int(status)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/PythonProject/recruitment/jobs/views.py", line 24, in joblist
    return HttpResponse(request, 'joblist.html', context)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/http/response.py", line 329, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/http/response.py", line 121, in __init__
    raise TypeError('HTTP status code must be an integer.')
TypeError: HTTP status code must be an integer.
2021-08-29 14:47:55,076 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-29 14:47:55,793 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-29 23:58:19,967 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:05:04,608 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:05:05,656 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:06:57,725 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:06:58,517 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:10:11,992 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:10:12,917 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:10:22,424 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:10:23,041 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:12:16,944 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:12:17,728 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:15:44,981 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:15:45,865 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:16:23,999 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:16:24,749 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:16:42,462 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:16:42,941 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:18:45,963 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/urls.py changed, reloading.
2021-08-30 00:18:46,729 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:19:19,745 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/urls.py changed, reloading.
2021-08-30 00:19:20,423 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:19:36,099 django.request 224 ERROR    Internal Server Error: /resume/add/
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: /resume_form.html
2021-08-30 00:21:46,990 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:21:47,880 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:21:56,374 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:21:56,906 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:27:19,451 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 00:27:20,415 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:31:52,639 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:35:40,333 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/admin.py changed, reloading.
2021-08-30 00:35:41,165 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:36:39,663 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/admin.py changed, reloading.
2021-08-30 00:36:40,463 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:36:52,114 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/admin.py changed, reloading.
2021-08-30 00:36:52,928 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:38:28,229 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/admin.py changed, reloading.
2021-08-30 00:38:28,998 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:38:49,896 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-30 00:38:51,087 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:41:08,260 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-30 00:41:09,107 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:42:09,830 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/admin.py changed, reloading.
2021-08-30 00:42:10,719 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:42:47,298 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/admin.py changed, reloading.
2021-08-30 00:42:48,141 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:44:50,074 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/urls.py changed, reloading.
2021-08-30 00:44:50,931 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:45:29,155 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-30 00:45:29,876 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:46:21,085 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-30 00:46:21,972 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:46:47,742 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-30 00:46:48,394 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:47:29,088 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-30 00:47:29,777 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:47:56,283 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-30 00:47:56,889 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:48:38,706 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/interview/admin.py changed, reloading.
2021-08-30 00:48:39,228 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 00:51:54,390 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/admin.py changed, reloading.
2021-08-30 00:51:55,181 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 15:03:39,266 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 15:05:28,790 django.request 224 ERROR    Internal Server Error: /resume/add/
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/Users/liuhao/PythonProject/recruitment/jobs/views.py", line 85, in form_valid
    return HttpResponseRedirect(self.get_success_url())
NameError: name 'HttpResponseRedirect' is not defined
2021-08-30 15:07:27,260 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/views.py changed, reloading.
2021-08-30 15:07:27,767 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
2021-08-30 15:08:56,875 django.request 224 ERROR    Internal Server Error: /admin/jobs/resume/
Traceback (most recent call last):
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1723, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/Users/liuhao/opt/anaconda3/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1408, in response_action
    response = func(self, request, queryset)
  File "/Users/liuhao/PythonProject/recruitment/jobs/admin.py", line 26, in enter_interview_process
    candidate.created_date = datetime.now()
NameError: name 'datetime' is not defined
2021-08-30 15:09:52,735 django.utils.autoreload 251 INFO     /Users/liuhao/PythonProject/recruitment/jobs/admin.py changed, reloading.
2021-08-30 15:09:53,531 django.utils.autoreload 637 INFO     Watching for file changes with StatReloader
